services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: write_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data

  postgres_r2:
    image: postgres:16
    container_name: postgres_r2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: read_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    restart: always
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 512M
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - 0.0.0.0:9092
      - --advertise-kafka-addr
      - redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"
  

  write_api:
    build: ../app/write-api
    container_name: write_api
    environment:
      PORT: 3001
      PGHOST: host.docker.internal
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: write_db
      PGPORT: 5432
      KAFKA_BROKERS: redpanda:9092
      KAFKA_TOPIC: product-update
    depends_on:
      - postgres
      - redpanda
    ports:
      - "3001:3001"

  read_api_r1:
    build: ../app/read-api
    container_name: read_api_r1
    environment:
      PORT: 3002
      REGION: R1
      PGHOST: host.docker.internal
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: write_db
      PGPORT: 5432
    depends_on:
      - postgres
    ports:
      - "3002:3002"

  read_api_r2:
    build: ../app/read-api
    container_name: read_api_r2
    environment:
      PORT: 3003
      REGION: R2
      PGHOST: host.docker.internal
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: read_db
      PGPORT: 5433
    depends_on:
      - postgres_r2
    ports:
      - "3003:3003"

  replicator:
    build: ../app/replicator
    container_name: replicator
    environment:
      KAFKA_BROKERS: redpanda:9092
      KAFKA_TOPIC: product-update
      GROUP_ID: replicator-group
      PGHOST: host.docker.internal
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: read_db
      PGPORT: 5433
    depends_on:
      - redpanda
      - postgres_r2
    ports:
      - "3004:3004"


volumes:
  pgdata1:
  pgdata2:
